spring:
  profiles:
    active: prod
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/escola
      username: postgres
      password: 1234
      maximum-pool-size: 15
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false